config/routes.rb
Rails.application.routes.draw do
  post 'like/:micropost_id' => 'likes#like', as: 'like'
  delete 'unlike/:micropost_id' => 'likes#unlike', as: 'unlike'


  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  get 'users/new'


  root             'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get "/tweet" => "tweet#timeline"
  get "/signout_twitter" => "tweet#destroy"

  get "/auth/:provider/callback" => "tweet#create"

  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :tags, only:[:new, :create, :destroy, :show]
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :microposts, only: [:create, :destroy, :show]
  resources :relationships, only: [:create, :destroy]
  resources :comments, only: [:create, :destroy]
  end

app/views/shared/_comment_form.html.erb
<%= form_for(@comment, html: { multipart: true }) do |f| %>
<%= render 'shared/error_messages', object: f.object%>

<div class="field">
  <span class="count">

  </span>
  <%= f.text_area :content, placeholder: "本文を入力してください"%>
</div>
<%= f.submit "Post", class: "btn btn-primary" %>
<% end %>

app/views/shared/_detail.html.erb
<div class="comment form">
<%= render 'shared/comment_form'%>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
<div id="error_explanation">
  <div class="alert alert_danger">
    The form contains <%= pluralize(object.errors.count, "error") %>.
  </div>
  <ul>
    <% object.errors.full_messages.each do |msg|%>
    <li>
      <%= msg %>
    </li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_index.html.erb
<% provide(:title, 'All tags') %>
<h1>タグ一覧</h1>

<ul class = "tags_index">
      <%= render @tags %>
</ul>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost, html: { multipart: true }) do |f| %>
<%= render 'shared/error_messages', object: f.object%>

<div class="idea-title">
  <p>タイトル</p>
  <%= f.text_area :title, placeholder: "タイトルを入力してください", class: 'form-control' %>
</div>
<div class="field">
  <p>本文</p>
  <%= f.text_area :content, placeholder: "本文を入力してください"%>
</div>
<%= f.submit "投稿", class: "btn btn-primary" %>
<span class="picture">
  <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
</span>
<% end %>

<script type="text/javascript">
  $('#micropost_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('ファイル容量は最大5MBです');
    }
  });
</script>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= users_path(@user) %>" >
    <strong id="microposts" class="stat">
      <%= @user.microposts.count %>
      </strong>
      件の投稿
      </a>
  <a href="<% following_user_path(@user) %>">
    <strong id="followings" class="stat">
      <%= @user.following.count %>
    </strong>
    フォロー
  </a>
  <a href="<% followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    フォロワー
  </a>


</div>

app/views/shared/_user_info.html.erb
<div class="current_user_image">
<%= link_to gravatar_for(current_user, size: 50), current_user %>
</div>
<h1><%= current_user.name %></h1>
<span><%= link_to "プロフィールを見る", current_user %></span>