config/routes.rb
Rails.application.routes.draw do
  post 'like/:micropost_id' => 'likes#like', as: 'like'
  delete 'unlike/:micropost_id' => 'likes#unlike', as: 'unlike'


  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  get 'users/new'


  root             'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get "/tweet" => "tweet#timeline"
  get "/signout_twitter" => "tweet#destroy"

  get "/auth/:provider/callback" => "tweet#create"

  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :tags, only:[:new, :create, :destroy, :show]
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :microposts, only: [:create, :destroy, :show]
  resources :relationships, only: [:create, :destroy]
  resources :comments, only: [:create, :destroy]
  end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  belongs_to :user
  has_many :tags, through: :adapters
  has_many :adapters
  has_many :likes, dependent: :destroy
  has_many :comments
  has_many :connectors

  default_scope -> { order(created_at: :desc) }
  mount_uploader :picture, PictureUploader
  validates :user_id, presence: true
  validates :content, presence: true
  validate :picture_size

  def like_user(user_id)
   likes.find_by(user_id: user_id)
  end

  private

  def picture_size
    if picture.size > 5.megabytes
      errors.add(:picture, "should be less than 5MB")
    end
  end

end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
    before_action :logged_in_user, only: [:create, :destroy]
    before_action :correct_user, only: :destroy

  def create
    @micropost = current_user.microposts.build(micropost_params)
    if @micropost.save
      flash[:success] = "投稿が完了しました"
      redirect_to root_url
    else
      @feed_items = []
      render 'static_pages/home'
    end
  end

  def destroy
    @micropost.destroy
    flash[:success] = "投稿が削除されました"
    redirect_to request.referrer || root_url
  end

  def show
    # params id からmicropostの情報を検索
    @micropost = Micropost.find(params[:id])
    @comments = @micropost.comments
    @comment = Comment.new
  end


  private

    def micropost_params
      params.require(:micropost).permit(:content, :picture, :title, :tag_list)
    end

    def correct_user
      @micropost = current_user.microposts.find_by(id: params[:id])
      redirect_to root_url if @micropost.nil?
    end
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/views/microposts/_micropost.html.erb
<div class="idea">
  <div class="idea-info">
    <div class="post-icon">
    <%= link_to gravatar_for(micropost.user, size: 50), micropost.user %>
    </div>
    <div class="user-name">
    <%= link_to micropost.user.name, micropost.user %>
    </div>
  </div>
  <div class="idea-content">
    <div class="idea-text">
    <h1><%= micropost.title %></h1>
    <p><%= micropost.content %></p>
    </div>
    <%= image_tag micropost.picture.url if micropost.picture? %>
    <div class="timestamp">
      Posted <%= time_ago_in_words(micropost.created_at) %> ago.

      <% if current_user?(micropost.user) %>
      <%= link_to "削除", micropost, :method => :delete,
                                         data: { confirm: "本当に削除しますか？" } %>
      <% end %>
      <% if micropost.like_user(current_user.id)%>
        <%= link_to 'いいね！を取り消す', unlike_path(micropost.id), method: :delete %>
      <% else %>
        <%= link_to 'いいね！', like_path(micropost.id), method: :post %>
      <% end %>
        <%= link_to 'コメント', micropost_path(micropost.id) %>
    </div>
  </div>
</div>

app/views/microposts/show.html.erb
<div class="col-md-4">
  <%= form_for(@comment, html: { multipart: true }) do |f| %>
    <%= render 'shared/error_messages', object: f.object%>
    <div class="field">
      <%= hidden_field_tag 'id', @micropost.id %>
      <%= f.text_area :comment, placeholder: "本文を入力してください"%>
    </div>
  <%= f.submit "Comment", class: "btn btn-primary" %>
<% end %>
</div>


  <div class="idea" >
    <% @comments.each do |c| %>
      <% user = User.find(c.user_id)  %>
        <span class="idea-info">
        <%= link_to gravatar_for(user, size: 50), user %>
        <%= link_to user.name, user %></span>
        <span class="idea-content">
          <span class="idea-text"><%= c.comment %></span>
          <span class="timestamp">Commented <%= time_ago_in_words(c.created_at) %> ago.</span>
        </span>
    <% end %>
  </div>