config/routes.rb
Rails.application.routes.draw do
  post 'like/:micropost_id' => 'likes#like', as: 'like'
  delete 'unlike/:micropost_id' => 'likes#unlike', as: 'unlike'


  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  get 'users/new'


  root             'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get "/tweet" => "tweet#timeline"
  get "/signout_twitter" => "tweet#destroy"

  get "/auth/:provider/callback" => "tweet#create"

  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :tags, only:[:new, :create, :destroy, :show]
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :microposts, only: [:create, :destroy, :show]
  resources :relationships, only: [:create, :destroy]
  resources :comments, only: [:create, :destroy]
  end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
         <div class="container">
           <%=link_to "Scribble", root_path, id:"logo" %>
           <nav>
             <ul class="nav navbar-nav navbar-right">
               <li><%=link_to"ホーム",root_path %></li>
               <li><%=link_to"ヘルプ",help_path %></li>
               <% if logged_in? %>
                 <li><%= link_to "ユーザー", users_path %></li>
                 <li class="dropdown">
                   <a href="#" class="dropdown-toggle", data-toggle="dropdown">
                     アカウント<b class="caret"></b>
                   </a>
                   <ul class="dropdown-menu">
                     <li><%= link_to "プロフィール", current_user %></li>
                     <li><%= link_to "設定", edit_user_path(current_user) %></li>
                     <li class="divider"></li>
                     <li>
                       <%= link_to "ログアウト", logout_path, method: "delete" %>
                     </li>
                   </ul>
                 </li>
               <% else %>
                 <li><%= link_to "ログイン", login_path %></li>
               <% end %>
             </ul>
           </nav>
         </div>
         </header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
          <%= render 'layouts/header' %>
    <div class="container">
        <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
    <%= yield %>

    <!-- <div id="user_nav">
        <% if logged_in? %>
          ようこそ！ <%= session[:username] %>
        <% end %>
      </div> -->
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>